Candidate: CVE-2025-2953
PublicDate: 2025-03-31
References:
 https://www.cve.org/CVERecord?id=CVE-2025-2953
 https://github.com/pytorch/pytorch/issues/149274
 https://github.com/pytorch/pytorch/issues/149274#issue-2923122269
 https://vuldb.com/?ctiid.302006
 https://vuldb.com/?id.302006
 https://vuldb.com/?submit.521279
Description:
 A vulnerability, which was classified as problematic, has been found in
 PyTorch 2.6.0+cu124. Affected by this issue is the function
 torch.mkldnn_max_pool2d. The manipulation leads to denial of service. An
 attack has to be approached locally. The exploit has been disclosed to the
 public and may be used.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L [3.3 LOW]

Patches_pytorch:
upstream_pytorch: needs-triage
focal_pytorch: DNE
jammy_pytorch: needs-triage
esm-apps/jammy_pytorch: needs-triage
noble_pytorch: DNE
oracular_pytorch: needs-triage
devel_pytorch: needs-triage
