Candidate: CVE-2025-55557
PublicDate: 2025-09-25 16:15:00 UTC
References:
 https://www.cve.org/CVERecord?id=CVE-2025-55557
 https://gist.github.com/shaoyuyoung/0e7d2a586297ae9c8ed14d8706749efc
 https://github.com/pytorch/pytorch/issues/151738
 https://github.com/pytorch/pytorch/pull/151931
Description:
 A Name Error occurs in pytorch v2.7.0 when a PyTorch model consists of
 torch.cummin and is compiled by Inductor, leading to a Denial of Service
 (DoS).
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 cisa-adp: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H [7.5 HIGH]
 nvd: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H [7.5 HIGH]

Patches_pytorch:
upstream_pytorch: needs-triage
jammy_pytorch: needs-triage
esm-apps/jammy_pytorch: needs-triage
noble_pytorch: DNE
plucky_pytorch: needs-triage
questing_pytorch: needs-triage
devel_pytorch: needs-triage
