Candidate: CVE-2025-46149
PublicDate: 2025-09-25 15:16:00 UTC
References:
 https://www.cve.org/CVERecord?id=CVE-2025-46149
 https://gist.github.com/shaoyuyoung/4bcefba4004f8271e64b5185c95a248a
 https://github.com/pytorch/pytorch/issues/147848
 https://github.com/pytorch/pytorch/pull/147961
Description:
 In PyTorch before 2.7.0, when inductor is used, nn.Fold has an assertion
 error.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 cisa-adp: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N [5.3 MEDIUM]

Patches_pytorch:
upstream_pytorch: needs-triage
jammy_pytorch: needs-triage
esm-apps/jammy_pytorch: needs-triage
noble_pytorch: DNE
plucky_pytorch: needs-triage
devel_pytorch: needs-triage
