PublicDateAtUSN: 2022-06-18 16:15:00 UTC
Candidate: CVE-2021-46823
PublicDate: 2022-06-18 16:15:00 UTC
References:
 https://github.com/python-ldap/python-ldap/security/advisories/GHSA-r8wq-qrxc-hmcm
 https://exchange.xforce.ibmcloud.com/vulnerabilities/221507
 https://ubuntu.com/security/notices/USN-5508-1
 https://www.cve.org/CVERecord?id=CVE-2021-46823
Description:
 python-ldap before 3.4.0 is vulnerable to a denial of service when
 ldap.schema is used for untrusted schema definitions, because of a regular
 expression denial of service (ReDoS) flaw in the LDAP schema parser. By
 sending crafted regex input, a remote authenticated attacker could exploit
 this vulnerability to cause a denial of service condition.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H [6.5 MEDIUM]


Patches_python-ldap:
 upstream: https://github.com/python-ldap/python-ldap/pull/444/commits/31dbb4b075b4710e3adac7ac998a02aaeb2c5d3d
upstream_python-ldap: released (3.4.0-1)
bionic_python-ldap: released (3.0.0-1ubuntu0.2)
esm-infra/bionic_python-ldap: not-affected (3.0.0-1ubuntu0.2)
focal_python-ldap: released (3.2.0-4ubuntu2.1)
esm-infra/focal_python-ldap: not-affected (3.2.0-4ubuntu2.1)
impish_python-ldap: released (3.2.0-4ubuntu5.1)
jammy_python-ldap: released (3.2.0-4ubuntu7.1)
devel_python-ldap: not-affected (3.4.0-2)
